### ISSUE TITLE
Get orig tarball instructions incomplete

### ISSUE THREAD

**Issue by jpm-canonical** [canonical/ubuntu-maintainers-handbook#131]
https://github.com/canonical/ubuntu-maintainers-handbook/blob/d654e77a4180571b85aae7689d0424ebbc4b0e8f/PackageMerging.md?plain=1#L833-L841

The `git ubuntu export-orig` failed for me, and the link to how to do it manually doesn't work.

I ended up using `git ubuntu export-orig --for-merge`, which worked.

**Comment by jpm-canonical** [comment]
Not fully fixed yet. The link to doing it manually is still broken.

Currently using: 
`#get-orig-tarball-manually`
Should be:
`#get-the-orig-tarball-manually`

**Comment by panlinux** [comment]
FIxed in b46110e4cce85ec87d3ee368764ac73f8ebbefe3 with a trivial commit.
