### ISSUE TITLE
Add comment about `--CL--` in commit message during merge for git-ubuntu

### ISSUE THREAD

**Issue by mitchdz** [canonical/ubuntu-maintainers-handbook#135]
You may see something such as

```
--CL--
    - d/control: demote ipmitool and sbd dependencies to Suggests.
      fence-agents-{ipmilan,sbd} depend on packages in universe, instead
      of promoting them to main let's change the relationship to
      Suggests.
```
In the git commit message. This is used for git-ubuntu to generate the `debian/changelog` at the end of the merge without having to do weird formatting. This should be included in `./PackageMerging.md`.

**Comment by cpaelzer** [comment]
+1, explained this to one more person, time to add it
