### ISSUE TITLE
Discussion: Improve readability of example commands

### ISSUE THREAD

**Issue by dviererbe** [canonical/ubuntu-maintainers-handbook#83]
A lot of example commands are really hard to read, because they are really long. For example in [PackageTests.md](https://github.com/canonical/ubuntu-maintainers-handbook/blob/main/PackageTests.md):
```
$ autopkgtest -U -s -o dep8-mypackage-ppa --setup-commands="sudo add-apt-repository -y -u -s ppa:mylaunchpaduser/focal-mypackage-fixed-something-1234567" -B mypackage -- lxd autopkgtest/ubuntu/focal/amd64
```

This could be improved by just spreading the parameters over multiple lines. For example:

```bash
$ autopkgtest -U -s -B \
 -o dep8-mypackage-ppa \
 --setup-commands "sudo add-apt-repository -y -u -s \
   ppa:mylaunchpaduser/focal-mypackage-fixed-something-1234567" \
 mypackage \
 -- lxd autopkgtest/ubuntu/focal/amd64
```

Or even using the extended name of flags which is much more readable by newcomers. Advanced users should be able to figure out the short names of flags. For example:

```bash
$ autopkgtest \
 --apt-upgrade \
 --shell-fail \
 --output-dir dep8-mypackage-ppa \
 --setup-commands "sudo add-apt-repository \
   --yes \
   --update \
   --enable-source \
   ppa:mylaunchpaduser/focal-mypackage-fixed-something-1234567" \
 --no-built-binaries \
 mypackage \
 -- lxd autopkgtest/ubuntu/focal/amd64
```

Before I put in the effort I want to discuss if this change would be appreciated.

**Comment by s-makin** [comment]
In my opinion this change would be a massive improvement. Side-scrolling commands should always be avoided if possible, even if just to make the content more readable on a smaller screen (phone/tablet).

**Comment by s-makin** [comment]
Thanks for the help on this Dominik - as we discussed, I've implemented this suggestion across the UMH

**Comment by mitchdz** [comment]
Closing as #82 merged, and on visual inspection it looks great :)

**Comment by mitchdz** [comment]
FYI I looked through the other docs and didn't notice anything that stands out as needing this improvement, but definitely feel free to reopen if needed.
