### ISSUE TITLE
Patch Version Increment Clarification

### ISSUE THREAD

**Issue by holmanb** [canonical/ubuntu-maintainers-handbook#97]
From [the relevant section](https://github.com/canonical/ubuntu-maintainers-handbook/blob/main/VersionStrings.md#version-adding-a-change-in-ubuntu-as-a-stable-release-update):

> The overall scheme stays the same for [Stable release updates](https://wiki.ubuntu.com/StableReleaseUpdates). One still only changes the ubuntu revision section of [upstream_version]-[debian_revision]ubuntu[ubuntu_revision].
>
>> - Increment Y in the numeric ubuntuX.Y suffix, like: ubuntu3.1 -> ubuntu3.2.
>> - If this is the first change via the SRU process, add the .1 suffix, like: ubuntu3 -> ubuntu3.1.
>> - If no ubuntuX was present before, then set ubuntu0.1 which will represent that there was no Ubuntu delta (0) before this upload which is the first to add a change (.1).
>> - If two releases have the same version, then this would make the package non upgradeable and cause a version conflict (two builds, but not the same). To resolve this, add the numeric YY.MM release version in between ubuntuX and the increment .1. For Jammy that might look like ...ubuntu3.22.04.1

If a stable release update release includes an Ubuntu delta (i.e. diff from upstream release), should this cause the package version to increment the patch delta `ubuntuY`? Or should this cause the package version to increment the SRU increment `ubuntu0.Y` (unconditionally follow bullet 1)? 

When, if ever, would a delta counter would be incremented in SRU?

**Comment by holmanb** [comment]
> -> Example in detail: _Adding a change to `2.0-2` in a stable Ubuntu release will use `2.0-2ubuntu0.1`_
> +> Example in detail: _Adding a change to `2.0-2` in a stable Ubuntu release will use `2.0-2ubuntu0.1`. This first .1 change can include any supplemental debian packaging changes or patches applicable to the stable release._

Thanks for the proposal @blackboxsw. Lets `s/can/must/` or similar, "can" implies an alternate option, and I think we've settled out of band that during SRU there is not.

**Comment by blackboxsw** [comment]
Thanks @holmanb I put that comment and dropped the #100 on the wire for any language improvements folks may want to better express the restriction to use `.1` always on first SRU.

**Comment by cpaelzer** [comment]
> If a stable release update release includes an Ubuntu delta (i.e. diff from upstream release), should this cause the package version to increment the patch delta ubuntuY?

No, stable updates release updates always change the .x and if no Y is there is becomes 0.1 as outlined.

> Or should this cause the package version to increment the SRU increment ubuntu0.Y (unconditionally follow bullet 1)?

Yes
